output_dir: "model_checkpoint/"
device: 'cuda:0'
dataset:
  augmentation:
    rotation_range: 10
  train_dir: 'train.csv'
  val_dir: 'val.csv'
  test_dir: 'test.csv'
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  
model:
  base: 'resnet50'
  pretrained: true
  multilabel: false
  input_size: [224, 224]
  num_classes: 2
  pretrained_path: None

optimizer:
  pretrained_path: None

train:
  batch_size: 64
  optimizer: 'adam'
  lr: 0.00001
  num_epochs: 100

val:
  batch_size: 64

test:
  batch_size: 256

custom_cb:
  patience: 5
  metric: 'f1_score'
  mode: 'max'

logger:
  api_key: "<COMET-ML-API-KEY>"
  workspace: "clayrisee"
  project_name: "tea_leaf_classification"